-- FRAUD_HACKATHON project setup
-- Creates the database, schema, and warehouse used by this project.

CREATE DATABASE IF NOT EXISTS FRAUD_HACKATHON;
CREATE SCHEMA IF NOT EXISTS FRAUD_HACKATHON.RAW;

CREATE WAREHOUSE IF NOT EXISTS FRAUD_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;
