-- FRAUD_FLAGS view
-- Flags TRANSFER/CASH_OUT transactions that drained the origin account,
-- flags overnight-window transactions, and rolls both into a simple RISK_SCORE.

USE DATABASE FRAUD_HACKATHON;
USE SCHEMA RAW;

CREATE OR REPLACE VIEW FRAUD_FLAGS AS
SELECT
    STEP,
    TYPE,
    AMOUNT,
    NAMEORIG,
    OLDBALANCEORG,
    NEWBALANCEORIG,
    NAMEDEST,
    OLDBALANCEDEST,
    NEWBALANCEDEST,
    ISFRAUD,
    ISFLAGGEDFRAUD,
    (TYPE IN ('TRANSFER', 'CASH_OUT')
        AND ABS(AMOUNT - OLDBALANCEORG) <= 0.01
        AND OLDBALANCEORG > 0) AS IS_BALANCE_DRAIN,
    (MOD(STEP, 24) BETWEEN 0 AND 8) AS IS_OVERNIGHT,
    (CASE WHEN (TYPE IN ('TRANSFER', 'CASH_OUT')
                AND ABS(AMOUNT - OLDBALANCEORG) <= 0.01
                AND OLDBALANCEORG > 0) THEN 2 ELSE 0 END
     + CASE WHEN (MOD(STEP, 24) BETWEEN 0 AND 8) THEN 1 ELSE 0 END) AS RISK_SCORE
FROM FRAUD_HACKATHON.RAW.PAYSIM;
